# Generated by Django 3.0.7 on 2020-06-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThrottleApp', '0002_auto_20200605_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='startend',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='starttime',
            new_name='start_time',
        ),
    ]
